name: CI for Pull Requests

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev , master ]

jobs:
  Build_Stateless_solution:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build Stateless solution
      run: dotnet build  Stateless.sln --configuration Release --no-restore
      
    - name: Test Stateless
      run: dotnet test --no-restore --no-build --configuration Release
      
  Publish_alpha_version:
    if: github.branch == 'dev'
    runs-on: windows-latest
    steps:
    - name: Prepare package
      run: dotnet pack src/stateless/stateless.csproj --version-suffix dev-${{github.run_id}} --configuration Debug
    - name: Publish package
      run: dotnet nuget push src\stateless\bin\Debug\ -s nuget.org ---api-key ${{ secrets.NUGETAPIKEY }}
  
  Publish_Nuget_package:
    if: github.branch == 'master'
    runs-on: windows-latest
    steps:
    - name: Prepare package
      run: dotnet pack src/stateless/stateless.csproj --configuration Release
    - name: Publish package
      run: dotnet nuget push src\stateless\bin\Release\ -s nuget.org ---api-key ${{ secrets.NUGETAPIKEY }}
